### ISSUE TITLE
New User config file saved external to git controlled files and not overwritten after updates

### ISSUE THREAD

**Issue by gazpan** [gazpan/WebtroPie#14]
Changes in settings should write to a local file that is not under source control. The existing settings.cfg can still be used for defaults but the local file if exists overrides default settings.

This way, after a git pull, user preferences are retained.

**Comment by Darknior** [comment]
Very good idea :)
I will try it on the next update.

**Comment by gazpan** [comment]
Sorry I haven't done this yet, I posted this to remind me to add this feature, I keep thinking that every update is overwriting preferences so I need to do something about it.

**Comment by Darknior** [comment]
Yes every time i lost settings and path :( :p

**Comment by gazpan** [comment]
This should be ok now.

**Comment by Darknior** [comment]
Ok i have see you made it here : https://github.com/gazpan/WebtroPie/commit/54421f2c52846aa05bcec69bd1a41f11801451b5

And for my part it save here **/opt/retropie/supplementary/WebtroPie/app/config**
I have think you want to save it to **/home/pi/.webtropie** on the user directory and out of source code ... Tell me, if you prefer let it here, it's not a problem, i will add a LN link to my system to found setting files faster.

Other really important settings to add this file, because when i PULL i lost them, are PATH for media : 

```
<string name="uploadImageDirectory" value="/home/pi/RetroPie/medias/${system_name}/box front"/>
<string name="uploadMarqueeDirectory" value="/home/pi/RetroPie/medias/${system_name}/logos"/>
<string name="uploadVideoDirectory" value="/home/pi/RetroPie/medias/${system_name}/videos"/>
<string name="maxImageSize" value="720x720"/>
<string name="maxMarqueeSize" value="200x400"/>
```
Maybe you don't do it because for the moment there are not in the MENU.

**Comment by gazpan** [comment]
Hi, yes that's a good idea, I have mine installed under the home directory so didn't think of that, but now you mention it that it a better / more unixy way of doing it, I will do that later, it should only be a few lines more of code.

**Comment by gazpan** [comment]
Changed to .webtropie, also theme stretch also saved there in the same way

**Comment by Darknior** [comment]
I have try and it's ok and works perfectly.
Every time a change a setting it is record there.
I also have add the image sise and path and it works fine.

Now you can remove the **preferences.cfg** file from the source, or not ?
