### ISSUE TITLE
Add suffix to media

### ISSUE THREAD

**Issue by Darknior** [gazpan/WebtroPie#39]
Doc : https://github.com/retropie/retropie-setup/wiki/scraper

>  -image_suffix suffix
    	The suffix added after rom name when creating image files. (default "-image")
  -marquee_suffix suffix
    	The suffix added after rom name when creating marquee files. (default "-marquee")
  -video_suffix suffix
    	The suffix added after rom name when creating video files. (default "-video")

If you use default settings, UniversalXMLScrapper or ES use them because they put all the images in the same directory with the same name than the game Rom. Suffix is the only solution to not overwrite images...

To add them you must add 3 new input to options ... leave them empty by default please.
But i think it can be cool to add "**placeholder**" to these inputs to help user : https://www.w3schools.com/tags/att_input_placeholder.asp

Directory Placeholder : /home/pi/.emulationstation/downloaded_images/${system_name}
If i remember fine ... because i don't use it.

**Comment by Darknior** [comment]
Cool it's working fine :)
If you don't forgot for placeholder you can close this issue :)

I read your wiki : https://github.com/gazpan/WebtroPie/wiki/Settings#upload
But i discover this option **LogThemeStyles** i can't see for the moment ... 
It is really excellent if you had some feature like this one to help skin makers ;)
Maybe i will found some ideas when i will try to release my final skin.

**Comment by gazpan** [comment]
just reading above again, do you think I should set the defaults to "-image", "-marquee", "-video" or blank ?

yes, I'll keep open until after placeholders

LogThemeStyles can only be set in the settings.cfg files, I use it sometimes when a z-index is wrong or something looks in the wrong place, I might then look at the theme files and find where I think it should go then compare this to WebtroPie thinks it should go and then check if there is something wrong with the logic, usually a problem is because of a duplicate element in multiple combined views or include files or a wrong tag.

The output isn't very freindly, it just shows all the elements for a view, then drill to say the theme attributes then drill again to see the css style that's been generated.

For themers I though maybe they could hold a certain key down and then mouse over an element and drag it or resize it and show the position / size in theme units, it would be very complicated to try and save the change in many cases since the attributes could stored in so many different places in so many different ways, but I'm sure there is an opportunity to do something useful for themers.

**Comment by Darknior** [comment]
No for "-image", "-marquee", "-video" please, leave them blank. Many people don't use them. Just write them with PLACEHOLDER ;)

Ok i see, maybe later add a new checkbox to activate/show a développer option menu :)
Where you can add some new feature for them.
I must try this option to understand it ...

> For themers I though maybe they could hold a certain key down and then mouse over an element and drag it or resize it and show the position / size

WOAW it is fantastic if you can do it !!!!!
It will help a lot. Not important to save, so complicated, so many files possible, but if it is possible with a 
bubble or a flying info popup to have the element info like size, position ... or the element XML code ... it will be the best skin editor ever lol
If you have a list of what you can do, i can try to imagine how to show and use it on Webtropie ?
We can create a special ISSUE for it :)
Thanks

**Comment by gazpan** [comment]
yes, maybe like the media preview when you mouse over a text, image, rating etc (holding down a special key or after setting a mode) then maybe the border is dotted (like uploading) and there's info of dimensions, position, z-index (like preview) and either something to click to copy xml to clipboard / show bubble or right click ?

**Comment by gazpan** [comment]
... a little worry is though, that it's implying that WebtroPie is 100% accurate at displaying themes but it isn't there yet so I'd have to warn people that it's just for help and not definitive.

**Comment by gazpan** [comment]
While I added the local fix, I added placeholders for the uploads menu, unfortunately for normal text I chose grey on white like ES, so, getting a grey in-between which doesn't look as strong as normal text but looks faded enough and can still see it didn't leave much of an option, I made it italic to try to show the difference more...

**Comment by Darknior** [comment]
> ... a little worry is though, that it's implying that WebtroPie is 100% accurate at displaying themes but it isn't there yet so I'd have to warn people that it's just for help and not definitive.

Yes for sure ... and you will update it in time ...
No problem.

**Comment by Darknior** [comment]
All is working fine for me, i think you can close this issue :)
Next one ;)

**Comment by gazpan** [comment]
Thanks :)
