### ISSUE TITLE
BUG: <default> images not working fine

### ISSUE THREAD

**Issue by Darknior** [gazpan/WebtroPie#50]
We already speak about this **TAG** before, **<images>** can have a **default PATH** if the image file is not found.

Exemple : 

```
			<image name="bg-image" extra="true">
				<origin>0 0</origin>
				<pos>0 0</pos>
				<size>1 1</size>
				<path>./${system.theme}/screenshot-${langue}.jpg</path>
				<default>./${system.theme}/background.jpg</default>
				<color>ffffffff</color>
				<tile>false</tile>
				<zIndex>5</zIndex> <!-- Default 10 for extra -->
			</image>
```

**Comment by Darknior** [comment]
I have think today that maybe it's hard to add this feature ?
maybe you can read the XML, take the IMAGE ELEMENT and his TAGs.
If the IMAGE has a tag DEFAULT, before display the PATH (image) you could try to read the file in Ajax.
If the file exist you show it, if you have a 404 error you display the DEFAULT.

You have an exemple in SEGA SATURN in my Theme because i don't make any French image that are same than US images. I use the default option.

**Comment by gazpan** [comment]
It should be ok, I already wrote a directive in the onLoadImage.js file, all I have to do is add an attribute to any img tag like this
```
 on-load-image="vm.mediaLoaded($event, width, height, size, mtime)"
```
... and when the image loads (or not) it calls that function and sends all the information in the parameters, so I expect I just need to check if the size is zero, or maybe something in the event will tell me, and then if not switch the source to the default value.

I've already pretty much done this, except I'm just trying to find an example to test it out so opened up the editor to look at the Saturn system on your theme, the versions I have (one from your image download and one from git) both seem ok, but no problem I'll just edit it to break it.

So, I can do it and will do it anyway but just curious, is this going away from what ES does?, is it going to be a new feature or does it already do this and I just misread the documentation - (or it's not very clear?)

 - default  : type: PATH.
     Path to default image file. Default image will be displayed when selected game does not have an image.

.. which to me says 'if the game has no image metadata' then show this image, and I wouldn't be sure from that if it was just an extra attribute for the <image name="md-image"> or if it's any number of static images which all appear when the game image is blank, ... either way it's not really the same as, if the PATH image doesn't load or is blank then load DEFAULT, if that's what it does then maybe that should go in the wiki instead of what it does say.

... but anyway, I'll still do it as suggested but was just curious.

**Comment by Darknior** [comment]
Hooo for the moment i only use it for my theming images like system logo, system background, system console photo etc ...
But your question is interesting, i think we can use it too to show an image if the COVER or LOGO is not existing.

For the VIDEO the default image is the SNAPSHOT image now like i write it to you [here](https://github.com/gazpan/WebtroPie/issues/44).
And the snapshot will use same settings than the video if maxsize, there is a bug on ES with only size.
We can also configure to show this snapshot before video with a custom delay.

**Comment by Darknior** [comment]
I have quickly try this : 

```
			<image name="md_image">
				<origin>0 0</origin>
				<pos>0.0255 0.0639</pos> <!-- Left align -->
				<maxSize>0.3766 0.6689</maxSize>
				<default>./${system.theme}/test.jpg</default>
				<zIndex>30</zIndex> <!-- Default -->
			</image>
```

And it works fine on ES <3
We can put default image, i will create some now for my skin :p

**Comment by gazpan** [comment]
This should work now for game image based elements and non game/system images.
I also fixed another bug with system variables.

**Comment by Darknior** [comment]
Excellent it works for most of the images :)

It only bug on Caroussel for me : 

```
	<view name="system">
		<image name="logo">
			<path>./system-logo-gray-${langue}.png</path>
			<default>./system-logo-gray-us.png</default>
		</image>
```
![sans titre-1](https://user-images.githubusercontent.com/3703317/38459740-069d62b8-3aae-11e8-9c4f-25b03bb6349c.jpg)

There it try to take the image **-FR** and don't try the **-US** one.
I have push on my **GIT** the **SATURN** new _images and XML_ where i have the bug if you want to try it.

**Comment by gazpan** [comment]
Thanks I will have a look

**Comment by gazpan** [comment]
I think I fixed this a while ago but it was tied up in some other changes which I've released now, I think that you should be able to see the missing system logo now.

thanks

**Comment by gazpan** [comment]
Thanks
