### ISSUE TITLE
Home menu fast patch

### ISSUE THREAD

**Issue by Darknior** [gazpan/WebtroPie#9]
Thanks for the cache : https://github.com/gazpan/WebtroPie/commit/a24206e45b581fda527cd144eab07071d5985f03

But if we want an instant move, a faster home menu, i don't know if it's possible, but we should move before showing the games counter.
Same in gamelist, let us moving before showing first game informations.

**Comment by gazpan** [comment]
I'll have a think about that, the key events depend on being focused on, inputs that are listening, ... well, yes I could focus on perhaps the filter or something while the list is loading so that you can switch before it's loaded. i will have a look at that thanks.

Note: I have changed the way the system / home screen works, you now no longer have to wait for the animation to finish, switching very fast messes up the animations a little but better more functional than pretty ! :)

**Comment by Darknior** [comment]
WOAW !!! excellent now system menu is really fast :D 
Thanks
So fast if i move 10 systems, i must stop and stand for LOGO lol

**Comment by gazpan** [comment]
Let me know otherwise but I think this can be closed now, fast enough in the home screen and faster in the game list screen (although since it is reloading a new page there is a small delay when before input has focus on something that can read key strokes).
